spring.jpa.open-in-view=false

# Force UTF-8 encoding across all HTTP requests and responses
server.servlet.encoding.charset=UTF-8
server.servlet.encoding.force=true
server.servlet.encoding.force-response=true
server.servlet.encoding.enabled=true